// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kazcwhshptkxolxnmpel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthemN3aHNocHRreG9seG5tcGVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODMwODAsImV4cCI6MjA3NDI1OTA4MH0.RECpXxgiJsuK7cFtitK13B51izNLVctE3ipcmrxXe0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});